name: Build Server

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
        
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"
          
      - name: Bundle the app
        working-directory: ./server
        run: cargo build --release

          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./target/release/cassowary-server